### PR TITLE
Add navbar to tribute page

### PR DESCRIPTION
**Pull request by Dcode-k**
@GDSC-SCTCE  Please review my pull request and merge it. Also suggest any further changes.

### CODE REVIEW

**Comment by GDSC-SCTCE** [comment]
> @GDSC-SCTCE Please review my pull request and merge it. Also suggest any further changes.

@Dcode-k  the drop down menu is not working

**Comment by Dcode-k** [comment]
what features should I include in dropdown?
please suggest.

**Comment by Dcode-k** [comment]
@GDSC-SCTCE  sir now I make the dropdown working.
Please review my PR#27 and merge it.

**Comment by Dcode-k** [comment]
suggest further changes if any.

**Comment by GDSC-SCTCE** [comment]
> suggest further changes if any.

Thank u @Dcode-k

**Pull request merged**
